---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lidarr
  name: lidarr
  namespace: media-acq
spec:
  selector:
    app: lidarr
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: lidarr
  name: lidarr
  namespace: media-acq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  serviceName: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - image: linuxserver/lidarr:1.4.5
        name: lidarr
        ports:
        - containerPort: 8686
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /config
        - name: music
          mountPath: /music
        - name: downloads
          mountPath: media/downloads
      volumes:
      - name: music
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/music
          readOnly: false
      - name: downloads
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/downloads
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: freenas-nfs-csi
      resources:
        requests:
          storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lidarr
  name: lidarr-lb
  namespace: media-acq
spec:
  ports:
  - port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app: lidarr
  type: LoadBalancer