apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: navidrome
  name: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  strategy: {}
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
      - image: deluan/navidrome:develop
        name: navidrome
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: navidrome
  name: navidrome-lb
spec:
  ports:
  - port: 4533
    protocol: TCP
    targetPort: 4533
  selector:
    app: navidrome
  type: LoadBalancer
