  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: graylog-deployment
    name: graylog-deployment
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: graylog-deployment
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: graylog-deployment
      spec:
        containers:
        - image: graylog/graylog:5.2
          imagePullPolicy: IfNotPresent
          name: graylog
          resources:
            requests:
              cpu: 200m
              memory: 0.5Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog-deployment
  name: graylog-deployment
  namespace: default
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: graylog-deployment
  sessionAffinity: None
  type: LoadBalancer
