---
apiVersion: v1               # DB volume
kind: PersistentVolume
metadata:
  name: postgres-0
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  nfs:
    path: /mnt/servicesTank/nextcloud/posgres-0
    server: 192.168.1.10

---
apiVersion: v1               # DB volume
kind: PersistentVolume
metadata:
  name: postgres-1
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  nfs:
    path: /mnt/servicesTank/nextcloud/posgres-1
    server: 192.168.1.10

---
apiVersion: v1               # DB volume
kind: PersistentVolume
metadata:
  name: postgres-2
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  nfs:
    path: /mnt/servicesTank/nextcloud/posgres-2
    server: 192.168.1.10