---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: canary
  labels:
    name: canary
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: qbittorrent
  labels:
    name: qbittorrent
---
apiVersion: v1
kind: Namespace
metadata:
  name: media