---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lidarr
    use: media-infra
  name: lidarr
  namespace: media-acq
spec:
  selector:
    app: lidarr
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: lidarr
    use: media-infra
  name: lidarr
  namespace: media-acq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  serviceName: lidarr
  template:
    metadata:
      labels:
        app: lidarr
        use: media-infra
    spec:
      containers:
      - image: linuxserver/lidarr:1.4.5
        name: lidarr
        ports:
        - containerPort: 8686
        resources:
          requests:
            cpu: "250m"
            memory: "250M"
          limits:
            cpu: "4000m"
            memory: "4G"
        volumeMounts:
        - name: data
          mountPath: /config
        - name: music
          mountPath: /music
        - name: downloads
          mountPath: media/downloads
        securityContext:
          allowPrivilegeEscalation: true # not a best practice. linuxserver.io requirement
          readOnlyRootFilesystem: false # not a best practice
          runAsNonRoot: false         # not a best practice. linuxserver.io containers require root privilege
#          capabilities:
#            drop: 
#            - all
#          runAsUser: 103060          # linuxserver.io containers require root privilege
      volumes:
      - name: music
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/music
          readOnly: false
      - name: downloads
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/downloads
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: freenas-nfs-csi
      resources:
        requests:
          storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lidarr
    use: media-infra
  name: lidarr-lb
  namespace: media-acq
spec:
  ports:
  - port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app: lidarr
  type: LoadBalancer