---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
    use: media-infra
  name: qbittorrent
  namespace: media-acq
spec:
  selector:
    app: qbittorrent
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: qbittorrent
    use: media-infra
  name: qbittorrent
  namespace: media-acq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  serviceName: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        use: media-infra
    spec:
      containers:
      - image: qbittorrentofficial/qbittorrent-nox:latest
        name: qbittorrent
        env:                  # qBittorrent container
          - name: PGID
            value: "3048"
          - name: PUID
            value: "3048"
          - name: UMASK
            value: "0002"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "250M"
          limits:
            cpu: "4000m"
            memory: "8G"
        volumeMounts:
        - name: data
          mountPath: /config
        - name: downloads
          mountPath: /media/downloads
        - name: videos
          mountPath: /media/videos
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: false
      - image: qmcgaw/gluetun:latest              # Gluetun Container
        name: gluetun
        resources: {}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "protonvpn"
        - name: VPN_TYPE
          value: "wireguard"
        - name: WIREGUARD_PRIVATE_KEY
          value: "yAJTj1bU4hJSVieG9Zhyl8NnFPmbv/hyYPg0VPG4gEk="
        - name: WIREGUARD_PUBLIC_KEY
          value: "houxrsE+RottYWy4pSsRM8ZEReqN0cEzPGtYOzmjOF0="
        - name: VPN_PORT_FORWARDING
          value: "on"
        - name: SERVER_HOSTNAMES
          value: "node-us-248.protonvpn.net"
        - name: PORT_FORWARD_ONLY
          value: "on"
        - name: DNS_ADDRESS
          value: "9.9.9.9"
      volumes:
      - name: downloads
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/downloads
          readOnly: false
      - name: videos
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/videos
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: freenas-nfs-csi
      resources:
        requests:
          storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
    use: media-infra
  name: qbittorrent-lb
  namespace: media-acq
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qbittorrent
  type: LoadBalancer