---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
    use: media-infra
  name: radarr
  namespace: media-acq
spec:
  selector:
    app: radarr
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: radarr
    use: media-infra
  name: radarr
  namespace: media-acq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  serviceName: radarr
  template:
    metadata:
      labels:
        app: radarr
        use: media-infra
    spec:
      containers:
      - image: linuxserver/radarr:5.0.3
        name: radarr
        ports:
        - containerPort: 7878
        resources:
          requests:
            cpu: "250m"
            memory: "250M"
          limits:
            cpu: "4000m"
            memory: "4G"
        volumeMounts:
        - name: data
          mountPath: /config
        - name: movies
          mountPath: /media/movies
        - name: downloads
          mountPath: media/downloads
        securityContext:
          allowPrivilegeEscalation: true # not a best practice. linuxserver.io requirement
          readOnlyRootFilesystem: false # not a best practice
          runAsNonRoot: false         # not a best practice. linuxserver.io containers require root privilege
#          capabilities:
#            drop: 
#            - all
#          runAsUser: 103060          # linuxserver.io containers require root privilege
      volumes:
      - name: movies
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/movies
          readOnly: false
      - name: downloads
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/downloads
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: freenas-nfs-csi
      resources:
        requests:
          storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
    use: media-infra
  name: radarr-lb
  namespace: media-acq
spec:
  ports:
  - port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
  type: LoadBalancer