apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: webserver-hl
  namespace: default
spec:
  selector:
    app: nextcloud-webserver
  clusterIP: None
  ports:
  - port: 80
    name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nextcloud-webserver
  name: webserver
  namespace: default
spec:
  serviceName: webserver-hl
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextcloud-webserver
  template:
    metadata:
      labels:
        app: nextcloud-webserver
    spec:
      containers:
      - image: nextcloud:27.1.3
        imagePullPolicy: IfNotPresent
        name: nextcloud
#        ports:
#        - containerPort: 80
#          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsUser: 10452
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: "freenas-nfs-csi"
      resources:
        requests:
          storage: 100Gi