apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: webserver-hl
  namespace: nextcloud
spec:
  selector:
    app: nextcloud-webserver
  clusterIP: None
  ports:
  - port: 80
    name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nextcloud-webserver
  name: webserver
  namespace: nextcloud
spec:
  serviceName: webserver-hl
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextcloud-webserver
  template:
    metadata:
      labels:
        app: nextcloud-webserver
    spec:
      containers:
      - image: nextcloud:27.1.5
        imagePullPolicy: IfNotPresent
        name: nextcloud
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: NEXTCLOUD_DATA_DIR
          value: /data
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: 3Uyen09JdPCsXnlSeRDw3s4sfJoaMeyM
        - name: MYSQL_HOST
          value: db-hl:3306
        volumeMounts:
        - name: data
          mountPath: /data
        - name: www
          mountPath: /var/www/html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsUser: 10452
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: "freenas-nfs-csi"
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: "freenas-nfs-csi"
      resources:
        requests:
          storage: 16Gi