apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: canary

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
  loadBalancerIP: 192.168.3.91

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: canary

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
  loadBalancerIP: 192.168.3.91