apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - xervato.com
      secretName: xervato-com-tls  # Replace with your Secret name
  rules:
    - host: xervato.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nextcloud-lb   # Name of the service
              port:
                number: 80 # Port number for the service