---                           
apiVersion: v1                # qBittorrent loadbalancer          
kind: Service
metadata:
  name: qbittorrent-lb
  namespace: qbittorrent
spec:
  selector: 
    app: qbittorrent
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: 6881-tcp
      port: 6881
      targetPort: 6881
    - name: 6881-udp
      port: 6881
      protocol: UDP
      targetPort: 6881
  type: LoadBalancer
  loadBalancerIP: 192.168.3.84

---                           
apiVersion: v1                # jellyseerr loadbalancer
kind: Service
metadata:
  name: jellyseerr-lb
  namespace: qbittorrent
spec:
  selector: 
    app: qbittorrent
  ports:
    - name: 5055-jellyseerr
      port: 80
      targetPort: 5055
  type: LoadBalancer
  loadBalancerIP: 192.168.3.88

---
apiVersion: apps/v1           # Deployment
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        fsGroup: 3048
      containers:
        - env:                  # qBittorrent container
            - name: PGID
              value: "3048"
            - name: PUID
              value: "3048"
            - name: TZ
              value: Cst/UTC
            - name: QBT_WEBUI_PORT
              value: "8080"
          image: qbittorrentofficial/qbittorrent-nox:latest
          name: qbittorrent
          ports:
            - containerPort: 8080
            - containerPort: 6881
            - containerPort: 6881
              protocol: UDP
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /config
              name: qb-config
            - mountPath: /media
              name: radarr-media
        - env:                      # jellyseerr container
            - name: PGID
              value: "103050"
            - name: PUID
              value: "103050"
            - name: TZ
              value: America/Chicago
          image: fallenbagel/jellyseerr:latest
          name: jellyseerr
          ports:
            - containerPort: 5055
              protocol: TCP
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr-config
        - image: qmcgaw/gluetun:latest              # Gluetun Container
          name: gluetun
          resources: {}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
          - name: VPN_SERVICE_PROVIDER
            value: "protonvpn"
          - name: VPN_TYPE
            value: "openvpn"
          - name: VPN_PORT_FORWARDING
            value: "on"
          - name: VPN_PORT_FORWARDING_PROVIDER
            value: "protonvpn"
          - name: OPENVPN_USER
            value: "cXYz2ypNjJIt2pJC+pmp"
          - name: OPENVPN_PASSWORD
            value: "0da5KkFMcwib01oNXcTcOSCgXCwIDV80"
          - name: SERVER_COUNTRIES
            value: "United States"
      restartPolicy: Always
      volumes:
        - name: qb-config              # qBittorrent volumes
          nfs:
            server: 192.168.1.10
            path: /mnt/servicesTank/qbittorrent
            readOnly: false
        - name: radarr-media           # Shared media volume
          nfs:
            server: 192.168.1.10
            path: /mnt/cpool1/media
            readOnly: false
        - name: jackett-config           # Jackett volumes
          nfs:
            server: 192.168.1.10
            path: /mnt/servicesTank/jackett
            readOnly: false
        - name: bazarr-config           # Bazarr volumes
          nfs:
            server: 192.168.1.10
            path: /mnt/servicesTank/bazarr
            readOnly: false
        - name: jellyseerr-config           # jellyseerr volumes
          nfs:
            server: 192.168.1.10
            path: /mnt/servicesTank/jellyseerr
            readOnly: false
        - name: sonarr-config              # Sonarr config volume
          nfs:
            server: 192.168.1.10
            path: /mnt/servicesTank/sonarr
            readOnly: false
        - name: media                         # Sonarr media volume
          nfs:
            server: 192.168.1.10
            path: /mnt/cpool1/media
            readOnly: false