apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy: {}
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: nextcloud:27.1.3-apache
        name: nextcloud
        env:
        - name: POSTGRES_USER
          value: dbadmin
        - name: POSTGRES_PASSWORD
          value: 8GQ8qLkZ_Afunm2hNW@h87XaMvysyB6M
        - name: POSTGRES_DB
          value: nextcloud-db
        - name: POSTGRES_HOST
          value: localhost
        resources: {}
        volumeMounts:
        - name: nextcloud-data-storage
          mountPath: /var/www/html
        securityContext:
          runAsUser: 103060
          allowPrivilegeEscalation: false
      - image: postgres:14-alpine
        name: nextcloud-db
        env:
        - name: POSTGRES_USER
          value: dbadmin
        - name: POSTGRES_PASSWORD
          value: 8GQ8qLkZ_Afunm2hNW@h87XaMvysyB6M
        - name: POSTGRES_DB
          value: nextcloud-db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        securityContext:
          runAsUser: 103058
          allowPrivilegeEscalation: false
        resources: {}
        volumeMounts:
        - name: nextcloud-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: nextcloud-data-storage
        persistentVolumeClaim:
          claimName: nextclouddata-pvc
      - name: nextcloud-db-storage
        persistentVolumeClaim:
          claimName: nextclouddb-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-lb
  namespace: nextcloud
spec:
  ports:
  - name: nextcloud-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nextcloud
  type: LoadBalancer
  loadBalancerIP: 192.168.3.80

---
apiVersion: v1              #Data volume
kind: PersistentVolume
metadata:
  name: nextclouddata-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /mnt/servicesTank/nextcloud_Data
    server: 192.168.1.10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextclouddata-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
  storageClassName: ""
  volumeName: nextclouddata-pv

---
apiVersion: v1               # DB volume
kind: PersistentVolume
metadata:
  name: nextclouddb-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /mnt/servicesTank/nextcloud_DB
    server: 192.168.1.10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextclouddb-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
  storageClassName: ""
  volumeName: nextclouddb-pv